Colon in header fix
aws/amazon-neptune-csv-to-rdf-converter pull request #11
Opened 2022-07-17 12:31 UTC by EwoutGelling

Fixed incorrect handling of escaped colons in header column names. Column names containing escaped colons (\:) are now handled according to spec (https://docs.aws.amazon.com/neptune/latest/userguide/bulk-load-tutorial-format-gremlin.html).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-07-20 19:23 UTC, floschmedding requested changes

2022-07-20 19:23 UTC, floschmedding commented on src/main/java/software/amazon/neptune/csv2rdf/NeptuneCsvUserDefinedColumn.java
>  	 * non-whitespace characters.
Please mention that colons can be escaped.

2022-07-20 19:23 UTC, floschmedding commented on src/main/java/software/amazon/neptune/csv2rdf/NeptuneCsvUserDefinedColumn.java
>  	private static final int GROUPS_IN_HEADER_PATTERN = 2;
Should be 3 now.

2022-07-20 19:23 UTC, floschmedding commented on src/test/java/software/amazon/neptune/csv2rdf/NeptuneCsvInputParserTest.java
> +	public void escapedColonInHeader() {
Maybe add a column containing a backslash without colon.

2022-07-21 09:34 UTC, EwoutGelling commented on src/main/java/software/amazon/neptune/csv2rdf/NeptuneCsvUserDefinedColumn.java
>  	private static final int GROUPS_IN_HEADER_PATTERN = 2;
No still 2, (?<!\\\\) is not a non-capturing group indicated by the ?

2022-07-21 09:35 UTC, EwoutGelling commented on src/test/java/software/amazon/neptune/csv2rdf/NeptuneCsvInputParserTest.java
> +	public void escapedColonInHeader() {
Good one, now that I think about it, the current solution I proposed does not function when the column name ends in a backslash such as: cName/:Int. I'll look into how the Neptune bulk loader processes this, will get back to you.

2022-07-21 18:31 UTC, floschmedding approved these changes

2022-07-21 18:33 UTC, merged